# Generated by Django 4.2.4 on 2023-08-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelloapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=290)),
                ('img', models.ImageField(upload_to='pics')),
                ('position', models.TextField()),
            ],
        ),
    ]
